package compsciia;

import compsciia.*;
import java.awt.CardLayout;
import java.util.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author Julio E Rego
 */
public class DMVFrame extends javax.swing.JFrame {
    
    private Database data;
    private FileHandler handle;
    private Person p;
    
    /**
     * Creates new form DMVFrame
     */
    public DMVFrame() {
        initComponents();
        jSorry.setVisible(false);
        jSorryAgain.setVisible(false);
        this.setLocationRelativeTo(null);
        data = new Database();
        handle = new FileHandler("data.txt");
        try {
            handle.scanFile(data);
        }
        catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(jFrame1, "File not found.");
        }
        data.updateTable(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        Main = new javax.swing.JPanel();
        Login = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jAdminUser = new javax.swing.JTextField();
        jAdminLogin = new javax.swing.JButton();
        jTestBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jAdminPass = new javax.swing.JPasswordField();
        ApplicantInfo = new javax.swing.JPanel();
        jAddBtn = new javax.swing.JButton();
        fNameField = new javax.swing.JTextField();
        lNameField = new javax.swing.JTextField();
        ageField = new javax.swing.JTextField();
        genderField = new javax.swing.JTextField();
        jGenderLabel = new javax.swing.JLabel();
        jFNameLabel = new javax.swing.JLabel();
        jLNameLabel = new javax.swing.JLabel();
        jAgeLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Test = new javax.swing.JPanel();
        jInfo1 = new javax.swing.JLabel();
        jInfo2 = new javax.swing.JLabel();
        jStartTestBtn = new javax.swing.JButton();
        jNextBtn = new javax.swing.JButton();
        jSorry = new javax.swing.JLabel();
        jSorryAgain = new javax.swing.JButton();
        Manager = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonRem = new javax.swing.JButton();
        jReturnBtn = new javax.swing.JButton();

        jFrame1.setUndecorated(true);
        jFrame1.setResizable(false);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(683, 384));
        setResizable(false);

        Main.setPreferredSize(new java.awt.Dimension(683, 384));
        Main.setLayout(new java.awt.CardLayout());

        Login.setBackground(new java.awt.Color(87, 74, 121));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Reaction Timing Test");

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("For Admin Use ONLY");

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Username");

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");

        jAdminUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdminUserActionPerformed(evt);
            }
        });

        jAdminLogin.setBackground(new java.awt.Color(62, 29, 149));
        jAdminLogin.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        jAdminLogin.setText("Login");
        jAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdminLoginActionPerformed(evt);
            }
        });

        jTestBtn.setBackground(new java.awt.Color(62, 29, 149));
        jTestBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        jTestBtn.setForeground(new java.awt.Color(255, 255, 255));
        jTestBtn.setText("Take the Test");
        jTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTestBtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("OR");

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTestBtn)
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel9))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jAdminUser, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jAdminPass, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jAdminLogin)))
                        .addGap(245, 245, 245))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(147, 147, 147))))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jTestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel7))
                    .addComponent(jAdminUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel8))
                    .addComponent(jAdminPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jAdminLogin)
                .addGap(45, 45, 45))
        );

        Main.add(Login, "LoginPage");

        ApplicantInfo.setBackground(new java.awt.Color(87, 74, 121));

        jAddBtn.setBackground(new java.awt.Color(62, 29, 149));
        jAddBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jAddBtn.setForeground(new java.awt.Color(255, 255, 255));
        jAddBtn.setText("Next");
        jAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddBtnActionPerformed(evt);
            }
        });

        fNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameFieldActionPerformed(evt);
            }
        });

        lNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameFieldActionPerformed(evt);
            }
        });

        ageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageFieldActionPerformed(evt);
            }
        });

        genderField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderFieldActionPerformed(evt);
            }
        });

        jGenderLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jGenderLabel.setForeground(new java.awt.Color(255, 255, 255));
        jGenderLabel.setText("Gender");

        jFNameLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jFNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        jFNameLabel.setText("First Name");

        jLNameLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLNameLabel.setText("Last Name");

        jAgeLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jAgeLabel.setForeground(new java.awt.Color(255, 255, 255));
        jAgeLabel.setText("Age");

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Please fill in the following information to begin the test");

        javax.swing.GroupLayout ApplicantInfoLayout = new javax.swing.GroupLayout(ApplicantInfo);
        ApplicantInfo.setLayout(ApplicantInfoLayout);
        ApplicantInfoLayout.setHorizontalGroup(
            ApplicantInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ApplicantInfoLayout.createSequentialGroup()
                .addGroup(ApplicantInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ApplicantInfoLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(ApplicantInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(ApplicantInfoLayout.createSequentialGroup()
                                .addGroup(ApplicantInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(ApplicantInfoLayout.createSequentialGroup()
                                        .addComponent(jGenderLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(genderField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ApplicantInfoLayout.createSequentialGroup()
                                        .addComponent(jFNameLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(46, 46, 46)
                                .addGroup(ApplicantInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(ApplicantInfoLayout.createSequentialGroup()
                                        .addComponent(jLNameLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ApplicantInfoLayout.createSequentialGroup()
                                        .addComponent(jAgeLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(ApplicantInfoLayout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jAddBtn)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        ApplicantInfoLayout.setVerticalGroup(
            ApplicantInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ApplicantInfoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(ApplicantInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFNameLabel)
                    .addComponent(jLNameLabel)
                    .addComponent(lNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(ApplicantInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGenderLabel)
                    .addComponent(genderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAgeLabel)
                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(jAddBtn)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        Main.add(ApplicantInfo, "ApplicantPage");

        Test.setBackground(new java.awt.Color(87, 74, 121));

        jInfo1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jInfo1.setForeground(new java.awt.Color(255, 255, 255));
        jInfo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jInfo1.setText("When the background color changes from red to green, click anywhere within the window.");

        jInfo2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jInfo2.setForeground(new java.awt.Color(255, 255, 255));
        jInfo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jInfo2.setText("This test measures your average reaction time after 5 attempts.");

        jStartTestBtn.setBackground(new java.awt.Color(62, 29, 149));
        jStartTestBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jStartTestBtn.setForeground(new java.awt.Color(255, 255, 255));
        jStartTestBtn.setText("Start");
        jStartTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStartTestBtnActionPerformed(evt);
            }
        });

        jNextBtn.setBackground(new java.awt.Color(62, 29, 149));
        jNextBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jNextBtn.setForeground(new java.awt.Color(255, 255, 255));
        jNextBtn.setText("Next");
        jNextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextBtnActionPerformed(evt);
            }
        });

        jSorry.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jSorry.setForeground(new java.awt.Color(255, 255, 255));
        jSorry.setText("I did not finish :( but this reflex test is really all I have left to program");

        jSorryAgain.setBackground(new java.awt.Color(193, 0, 38));
        jSorryAgain.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jSorryAgain.setForeground(new java.awt.Color(255, 255, 255));
        jSorryAgain.setText("Click here to go back to the main page");
        jSorryAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSorryAgainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TestLayout = new javax.swing.GroupLayout(Test);
        Test.setLayout(TestLayout);
        TestLayout.setHorizontalGroup(
            TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TestLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSorry)
                    .addGroup(TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jInfo1, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TestLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TestLayout.createSequentialGroup()
                        .addComponent(jStartTestBtn)
                        .addGap(283, 283, 283))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TestLayout.createSequentialGroup()
                        .addComponent(jNextBtn)
                        .addGap(292, 292, 292))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TestLayout.createSequentialGroup()
                        .addComponent(jSorryAgain)
                        .addGap(189, 189, 189))))
        );
        TestLayout.setVerticalGroup(
            TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TestLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jSorry)
                .addGap(18, 18, 18)
                .addComponent(jSorryAgain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jInfo2)
                .addGap(18, 18, 18)
                .addComponent(jInfo1)
                .addGap(18, 18, 18)
                .addComponent(jStartTestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jNextBtn)
                .addGap(82, 82, 82))
        );

        Main.add(Test, "TestPage");

        Manager.setBackground(new java.awt.Color(87, 74, 121));
        Manager.setPreferredSize(new java.awt.Dimension(683, 384));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Last Name", "First Name", "Gender", "Age", "Reaction Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jButtonRem.setBackground(new java.awt.Color(62, 29, 149));
        jButtonRem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jButtonRem.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRem.setText("Remove");
        jButtonRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemActionPerformed(evt);
            }
        });

        jReturnBtn.setBackground(new java.awt.Color(62, 29, 149));
        jReturnBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jReturnBtn.setForeground(new java.awt.Color(255, 255, 255));
        jReturnBtn.setText("Back to main page");
        jReturnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReturnBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManagerLayout = new javax.swing.GroupLayout(Manager);
        Manager.setLayout(ManagerLayout);
        ManagerLayout.setHorizontalGroup(
            ManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManagerLayout.createSequentialGroup()
                        .addGap(0, 129, Short.MAX_VALUE)
                        .addGroup(ManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManagerLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManagerLayout.createSequentialGroup()
                                .addComponent(jButtonRem)
                                .addGap(296, 296, 296))))
                    .addGroup(ManagerLayout.createSequentialGroup()
                        .addComponent(jReturnBtn)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        ManagerLayout.setVerticalGroup(
            ManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jReturnBtn)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRem)
                .addGap(25, 25, 25))
        );

        Main.add(Manager, "ManagerPage");

        getContentPane().add(Main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void jAdminUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdminUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAdminUserActionPerformed

    private void jAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdminLoginActionPerformed
        // TODO add your handling code here:
        if(jAdminUser.getText().equals("admin") && jAdminPass.getText().equals("admin")) {
            jAdminUser.setText("");
            jAdminPass.setText("");
            CardLayout card = (CardLayout) Main.getLayout();
            card.show(Main, "ManagerPage");
        } else if (jAdminUser.getText().equals("") || jAdminPass.getText().equals("")) {
            JOptionPane.showMessageDialog(jFrame1, "Missing login information.");
        } else {
            JOptionPane.showMessageDialog(jFrame1, "Incorrect login information.");
        }
        
    }//GEN-LAST:event_jAdminLoginActionPerformed

    private void jButtonRemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemActionPerformed
        // TODO add your handling code here:
        try {
            data.remPerson(jTable1.getSelectedRow());
            data.updateTable(jTable1);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(jFrame1, "No person was selected.");
        }
        try {
            handle.updateFile(data);
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(jFrame1, "File not found.");
        }
    }//GEN-LAST:event_jButtonRemActionPerformed

    private void jTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTestBtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) Main.getLayout();
        card.show(Main, "ApplicantPage");
        
    }//GEN-LAST:event_jTestBtnActionPerformed

    private void jAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddBtnActionPerformed
        // TODO add your handling code here:
        String fName = fNameField.getText();
        String lName = lNameField.getText();
        String gend = genderField.getText();
        String age = ageField.getText();
        p = new Person(fName, lName, gend, age);
        
        if(((fName.equals("") || lName.equals("")) || gend.equals("")) || age.equals("")) {
            JOptionPane.showMessageDialog(jFrame1, "One or more text fields is not filled out.");
        } else {
            data.addPerson(p);
            try {
                handle.updateFile(data);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(jFrame1, "File not found.");
            }
        }
        
        data.updateTable(jTable1);
        
        fNameField.setText("");
        lNameField.setText("");
        genderField.setText("");
        ageField.setText("");
        
        CardLayout card = (CardLayout) Main.getLayout();
        card.show(Main, "TestPage");
    }//GEN-LAST:event_jAddBtnActionPerformed

    private void fNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameFieldActionPerformed

    private void lNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameFieldActionPerformed

    private void ageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageFieldActionPerformed

    private void genderFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderFieldActionPerformed

    private void jReturnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReturnBtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) Main.getLayout();
        card.show(Main, "LoginPage");
    }//GEN-LAST:event_jReturnBtnActionPerformed

    private void jStartTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStartTestBtnActionPerformed
        // TODO add your handling code here:
        jInfo1.setVisible(false);
        jInfo2.setVisible(false);
        jStartTestBtn.setVisible(false);
        jNextBtn.setVisible(false);
        jSorry.setVisible(true);
        jSorryAgain.setVisible(true);
        Test.setBackground(new java.awt.Color(207, 60, 60));
    }//GEN-LAST:event_jStartTestBtnActionPerformed

    private void jNextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNextBtnActionPerformed

    private void jSorryAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSorryAgainActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) Main.getLayout();
        card.show(Main, "LoginPage");
    }//GEN-LAST:event_jSorryAgainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DMVFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DMVFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DMVFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DMVFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DMVFrame().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ApplicantInfo;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel Manager;
    private javax.swing.JPanel Test;
    private javax.swing.JTextField ageField;
    private javax.swing.JTextField fNameField;
    private javax.swing.JTextField genderField;
    private javax.swing.JButton jAddBtn;
    private javax.swing.JButton jAdminLogin;
    private javax.swing.JPasswordField jAdminPass;
    private javax.swing.JTextField jAdminUser;
    private javax.swing.JLabel jAgeLabel;
    private javax.swing.JButton jButtonRem;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jFNameLabel;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jGenderLabel;
    private javax.swing.JLabel jInfo1;
    private javax.swing.JLabel jInfo2;
    private javax.swing.JLabel jLNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jNextBtn;
    private javax.swing.JButton jReturnBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jSorry;
    private javax.swing.JButton jSorryAgain;
    private javax.swing.JButton jStartTestBtn;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jTestBtn;
    private javax.swing.JTextField lNameField;
    // End of variables declaration//GEN-END:variables
}
